version: "3.9"

services:
  brmed_api:
    build:
      context: .
    container_name: brmed_api
    ports:
      - "8000:8000"
    depends_on:
      - brmed_database
    tty: true
    volumes:
      - .:/app

  brmed_database:
    image: postgres
    container_name: ${CONTAINER_NAME}
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
